#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(shinythemes)

# Define UI for application that draws a histogram
ui <- fluidPage(theme = shinytheme("superhero"),
    navbarPage(
        "My First Application",
        tabPanel("Navbar 1",
                 sidebarPanel(
                     tags$h3("Input:"),
                     textInput("txt1", "Given Name:", "",),  # txt1 will be sent out to the server
                     textInput("txt2", "Surname:", "",), # txt2 will be sent out to server
                 ),
                 mainPanel(
                     h1("Header 1"),
                     h4("Output 1"),
                     verbatimTextOutput("txtout"),# txtout will be generated by server
                 )
                 
                 ),
        tabPanel("Navbar 2",
                 "Personal Information",
                 sidebarPanel(
                     tags$h3("What is your age:"),
                     textInput("txt3:","Age:",""),
                     tags$h3("Where do you live:"),
                     textInput("txt4:", "Country:",""),
                     tags$h4("Favourite Food:"),
                     textInput("txt5:","Food:","")
                ),
                 mainPanel(
                    h1("Header 2"),
                    h4("Output 2"),
                    verbatimTextOutput("txtout1"),
                 ),
                 
                 )
    )
)
# Define server logic required to draw a histogram
server <- function(input, output) {
    output$txtout <- renderText({
        paste(input$txt1, input$txt2, sep =" ")
    })
    output$txtout1 <- renderText({
        paste("My age is",input$txt3,
              "I am from",input$txt4,
              "and my favourite food is",input$txt5, sep = " ")
    })

}

# Run the application 
shinyApp(ui = ui, server = server)
